// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kk_scheduler/ServiceGet.proto

package kk_scheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceGet struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceGet) Reset() {
	*x = ServiceGet{}
	mi := &file_kk_scheduler_ServiceGet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGet) ProtoMessage() {}

func (x *ServiceGet) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_ServiceGet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ServiceGet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ServiceGet_builder) Build() *ServiceGet {
	m0 := &ServiceGet{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ServiceGet_Input struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ServiceName *string                `protobuf:"bytes,1,opt,name=ServiceName"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ServiceGet_Input) Reset() {
	*x = ServiceGet_Input{}
	mi := &file_kk_scheduler_ServiceGet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceGet_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGet_Input) ProtoMessage() {}

func (x *ServiceGet_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_ServiceGet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServiceGet_Input) GetServiceName() string {
	if x != nil {
		if x.xxx_hidden_ServiceName != nil {
			return *x.xxx_hidden_ServiceName
		}
		return ""
	}
	return ""
}

func (x *ServiceGet_Input) SetServiceName(v string) {
	x.xxx_hidden_ServiceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ServiceGet_Input) HasServiceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ServiceGet_Input) ClearServiceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ServiceName = nil
}

type ServiceGet_Input_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// ServiceName, leave empty to get all services
	ServiceName *string
}

func (b0 ServiceGet_Input_builder) Build() *ServiceGet_Input {
	m0 := &ServiceGet_Input{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ServiceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ServiceName = b.ServiceName
	}
	return m0
}

type ServiceGet_Output struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Service *PBRegisterService     `protobuf:"bytes,1,opt,name=Service"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServiceGet_Output) Reset() {
	*x = ServiceGet_Output{}
	mi := &file_kk_scheduler_ServiceGet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceGet_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGet_Output) ProtoMessage() {}

func (x *ServiceGet_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_ServiceGet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServiceGet_Output) GetService() *PBRegisterService {
	if x != nil {
		return x.xxx_hidden_Service
	}
	return nil
}

func (x *ServiceGet_Output) SetService(v *PBRegisterService) {
	x.xxx_hidden_Service = v
}

func (x *ServiceGet_Output) HasService() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Service != nil
}

func (x *ServiceGet_Output) ClearService() {
	x.xxx_hidden_Service = nil
}

type ServiceGet_Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Service *PBRegisterService
}

func (b0 ServiceGet_Output_builder) Build() *ServiceGet_Output {
	m0 := &ServiceGet_Output{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Service = b.Service
	return m0
}

var File_kk_scheduler_ServiceGet_proto protoreflect.FileDescriptor

const file_kk_scheduler_ServiceGet_proto_rawDesc = "" +
	"\n" +
	"\x1dkk_scheduler/ServiceGet.proto\x12\fkk_scheduler\x1a\x17kk_scheduler/Base.proto\"|\n" +
	"\n" +
	"ServiceGet\x1a)\n" +
	"\x05Input\x12 \n" +
	"\vServiceName\x18\x01 \x01(\tR\vServiceName\x1aC\n" +
	"\x06Output\x129\n" +
	"\aService\x18\x01 \x01(\v2\x1f.kk_scheduler.PBRegisterServiceR\aServiceB\x0fZ\r/kk_schedulerb\beditionsp\xe8\a"

var file_kk_scheduler_ServiceGet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_scheduler_ServiceGet_proto_goTypes = []any{
	(*ServiceGet)(nil),        // 0: kk_scheduler.ServiceGet
	(*ServiceGet_Input)(nil),  // 1: kk_scheduler.ServiceGet.Input
	(*ServiceGet_Output)(nil), // 2: kk_scheduler.ServiceGet.Output
	(*PBRegisterService)(nil), // 3: kk_scheduler.PBRegisterService
}
var file_kk_scheduler_ServiceGet_proto_depIdxs = []int32{
	3, // 0: kk_scheduler.ServiceGet.Output.Service:type_name -> kk_scheduler.PBRegisterService
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kk_scheduler_ServiceGet_proto_init() }
func file_kk_scheduler_ServiceGet_proto_init() {
	if File_kk_scheduler_ServiceGet_proto != nil {
		return
	}
	file_kk_scheduler_Base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_scheduler_ServiceGet_proto_rawDesc), len(file_kk_scheduler_ServiceGet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_scheduler_ServiceGet_proto_goTypes,
		DependencyIndexes: file_kk_scheduler_ServiceGet_proto_depIdxs,
		MessageInfos:      file_kk_scheduler_ServiceGet_proto_msgTypes,
	}.Build()
	File_kk_scheduler_ServiceGet_proto = out.File
	file_kk_scheduler_ServiceGet_proto_goTypes = nil
	file_kk_scheduler_ServiceGet_proto_depIdxs = nil
}
