// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common_pb/extend_method.proto

package common_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 认证拦截器 最多只能配置一个
type InterceptorAuth int32

const (
	InterceptorAuth_UNSPECIFIED InterceptorAuth = 0
	// JWT认证拦截器
	InterceptorAuth_JWT InterceptorAuth = 1
	// 内部调用拦截器
	InterceptorAuth_InternalOnly InterceptorAuth = 2
)

// Enum value maps for InterceptorAuth.
var (
	InterceptorAuth_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "JWT",
		2: "InternalOnly",
	}
	InterceptorAuth_value = map[string]int32{
		"UNSPECIFIED":  0,
		"JWT":          1,
		"InternalOnly": 2,
	}
)

func (x InterceptorAuth) Enum() *InterceptorAuth {
	p := new(InterceptorAuth)
	*p = x
	return p
}

func (x InterceptorAuth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterceptorAuth) Descriptor() protoreflect.EnumDescriptor {
	return file_common_pb_extend_method_proto_enumTypes[0].Descriptor()
}

func (InterceptorAuth) Type() protoreflect.EnumType {
	return &file_common_pb_extend_method_proto_enumTypes[0]
}

func (x InterceptorAuth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var file_common_pb_extend_method_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: ([]InterceptorAuth)(nil),
		Field:         60001,
		Name:          "kk_scheduler.interceptor_auth_list",
		Tag:           "varint,60001,rep,packed,name=interceptor_auth_list,enum=kk_scheduler.InterceptorAuth",
		Filename:      "common_pb/extend_method.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60002,
		Name:          "kk_scheduler.api_name",
		Tag:           "bytes,60002,opt,name=api_name",
		Filename:      "common_pb/extend_method.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// repeated kk_scheduler.InterceptorAuth interceptor_auth_list = 60001;
	E_InterceptorAuthList = &file_common_pb_extend_method_proto_extTypes[0]
	// optional string api_name = 60002;
	E_ApiName = &file_common_pb_extend_method_proto_extTypes[1]
)

var File_common_pb_extend_method_proto protoreflect.FileDescriptor

const file_common_pb_extend_method_proto_rawDesc = "" +
	"\n" +
	"\x1dcommon_pb/extend_method.proto\x12\fkk_scheduler\x1a google/protobuf/descriptor.proto*=\n" +
	"\x0fInterceptorAuth\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\a\n" +
	"\x03JWT\x10\x01\x12\x10\n" +
	"\fInternalOnly\x10\x02:s\n" +
	"\x15interceptor_auth_list\x12\x1e.google.protobuf.MethodOptions\x18\xe1\xd4\x03 \x03(\x0e2\x1d.kk_scheduler.InterceptorAuthR\x13interceptorAuthList:;\n" +
	"\bapi_name\x12\x1e.google.protobuf.MethodOptions\x18\xe2\xd4\x03 \x01(\tR\aapiNameB*Z(github.com/cruvie/kk-scheduler/common_pbb\beditionsp\xe8\a"

var file_common_pb_extend_method_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_pb_extend_method_proto_goTypes = []any{
	(InterceptorAuth)(0),               // 0: kk_scheduler.InterceptorAuth
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_common_pb_extend_method_proto_depIdxs = []int32{
	1, // 0: kk_scheduler.interceptor_auth_list:extendee -> google.protobuf.MethodOptions
	1, // 1: kk_scheduler.api_name:extendee -> google.protobuf.MethodOptions
	0, // 2: kk_scheduler.interceptor_auth_list:type_name -> kk_scheduler.InterceptorAuth
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_pb_extend_method_proto_init() }
func file_common_pb_extend_method_proto_init() {
	if File_common_pb_extend_method_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_pb_extend_method_proto_rawDesc), len(file_common_pb_extend_method_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_common_pb_extend_method_proto_goTypes,
		DependencyIndexes: file_common_pb_extend_method_proto_depIdxs,
		EnumInfos:         file_common_pb_extend_method_proto_enumTypes,
		ExtensionInfos:    file_common_pb_extend_method_proto_extTypes,
	}.Build()
	File_common_pb_extend_method_proto = out.File
	file_common_pb_extend_method_proto_goTypes = nil
	file_common_pb_extend_method_proto_depIdxs = nil
}
