// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kk_scheduler/TaskExecution.proto

package kk_scheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskExecutionStatus int32

const (
	TaskExecutionStatus_TASK_EXECUTION_STATUS_UNSPECIFIED TaskExecutionStatus = 0
	TaskExecutionStatus_TASK_EXECUTION_STATUS_RUNNING     TaskExecutionStatus = 1
	TaskExecutionStatus_TASK_EXECUTION_STATUS_COMPLETED   TaskExecutionStatus = 2
	TaskExecutionStatus_TASK_EXECUTION_STATUS_FAILED      TaskExecutionStatus = 3
)

// Enum value maps for TaskExecutionStatus.
var (
	TaskExecutionStatus_name = map[int32]string{
		0: "TASK_EXECUTION_STATUS_UNSPECIFIED",
		1: "TASK_EXECUTION_STATUS_RUNNING",
		2: "TASK_EXECUTION_STATUS_COMPLETED",
		3: "TASK_EXECUTION_STATUS_FAILED",
	}
	TaskExecutionStatus_value = map[string]int32{
		"TASK_EXECUTION_STATUS_UNSPECIFIED": 0,
		"TASK_EXECUTION_STATUS_RUNNING":     1,
		"TASK_EXECUTION_STATUS_COMPLETED":   2,
		"TASK_EXECUTION_STATUS_FAILED":      3,
	}
)

func (x TaskExecutionStatus) Enum() *TaskExecutionStatus {
	p := new(TaskExecutionStatus)
	*p = x
	return p
}

func (x TaskExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_kk_scheduler_TaskExecution_proto_enumTypes[0].Descriptor()
}

func (TaskExecutionStatus) Type() protoreflect.EnumType {
	return &file_kk_scheduler_TaskExecution_proto_enumTypes[0]
}

func (x TaskExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type TaskCreate struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCreate) Reset() {
	*x = TaskCreate{}
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCreate) ProtoMessage() {}

func (x *TaskCreate) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type TaskCreate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 TaskCreate_builder) Build() *TaskCreate {
	m0 := &TaskCreate{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type TaskUpdateStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskUpdateStatus) Reset() {
	*x = TaskUpdateStatus{}
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUpdateStatus) ProtoMessage() {}

func (x *TaskUpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type TaskUpdateStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 TaskUpdateStatus_builder) Build() *TaskUpdateStatus {
	m0 := &TaskUpdateStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type TaskAppendLog struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAppendLog) Reset() {
	*x = TaskAppendLog{}
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAppendLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAppendLog) ProtoMessage() {}

func (x *TaskAppendLog) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type TaskAppendLog_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 TaskAppendLog_builder) Build() *TaskAppendLog {
	m0 := &TaskAppendLog{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type TaskCreate_Input struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskName    *string                `protobuf:"bytes,1,opt,name=task_name,json=taskName"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TaskCreate_Input) Reset() {
	*x = TaskCreate_Input{}
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCreate_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCreate_Input) ProtoMessage() {}

func (x *TaskCreate_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskCreate_Input) GetTaskName() string {
	if x != nil {
		if x.xxx_hidden_TaskName != nil {
			return *x.xxx_hidden_TaskName
		}
		return ""
	}
	return ""
}

func (x *TaskCreate_Input) SetTaskName(v string) {
	x.xxx_hidden_TaskName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *TaskCreate_Input) HasTaskName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TaskCreate_Input) ClearTaskName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TaskName = nil
}

type TaskCreate_Input_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskName *string
}

func (b0 TaskCreate_Input_builder) Build() *TaskCreate_Input {
	m0 := &TaskCreate_Input{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TaskName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_TaskName = b.TaskName
	}
	return m0
}

type TaskCreate_Output struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCreate_Output) Reset() {
	*x = TaskCreate_Output{}
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCreate_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCreate_Output) ProtoMessage() {}

func (x *TaskCreate_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type TaskCreate_Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 TaskCreate_Output_builder) Build() *TaskCreate_Output {
	m0 := &TaskCreate_Output{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type TaskUpdateStatus_Input struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskName    *string                `protobuf:"bytes,1,opt,name=task_name,json=taskName"`
	xxx_hidden_Status      TaskExecutionStatus    `protobuf:"varint,2,opt,name=status,enum=kk_scheduler.TaskExecutionStatus"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TaskUpdateStatus_Input) Reset() {
	*x = TaskUpdateStatus_Input{}
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUpdateStatus_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUpdateStatus_Input) ProtoMessage() {}

func (x *TaskUpdateStatus_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskUpdateStatus_Input) GetTaskName() string {
	if x != nil {
		if x.xxx_hidden_TaskName != nil {
			return *x.xxx_hidden_TaskName
		}
		return ""
	}
	return ""
}

func (x *TaskUpdateStatus_Input) GetStatus() TaskExecutionStatus {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Status
		}
	}
	return TaskExecutionStatus_TASK_EXECUTION_STATUS_UNSPECIFIED
}

func (x *TaskUpdateStatus_Input) SetTaskName(v string) {
	x.xxx_hidden_TaskName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *TaskUpdateStatus_Input) SetStatus(v TaskExecutionStatus) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *TaskUpdateStatus_Input) HasTaskName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TaskUpdateStatus_Input) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TaskUpdateStatus_Input) ClearTaskName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TaskName = nil
}

func (x *TaskUpdateStatus_Input) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Status = TaskExecutionStatus_TASK_EXECUTION_STATUS_UNSPECIFIED
}

type TaskUpdateStatus_Input_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskName *string
	Status   *TaskExecutionStatus
}

func (b0 TaskUpdateStatus_Input_builder) Build() *TaskUpdateStatus_Input {
	m0 := &TaskUpdateStatus_Input{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TaskName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_TaskName = b.TaskName
	}
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Status = *b.Status
	}
	return m0
}

type TaskUpdateStatus_Output struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskUpdateStatus_Output) Reset() {
	*x = TaskUpdateStatus_Output{}
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUpdateStatus_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUpdateStatus_Output) ProtoMessage() {}

func (x *TaskUpdateStatus_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type TaskUpdateStatus_Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 TaskUpdateStatus_Output_builder) Build() *TaskUpdateStatus_Output {
	m0 := &TaskUpdateStatus_Output{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type TaskAppendLog_Input struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskName    *string                `protobuf:"bytes,1,opt,name=task_name,json=taskName"`
	xxx_hidden_Log         *string                `protobuf:"bytes,2,opt,name=log"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TaskAppendLog_Input) Reset() {
	*x = TaskAppendLog_Input{}
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAppendLog_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAppendLog_Input) ProtoMessage() {}

func (x *TaskAppendLog_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskAppendLog_Input) GetTaskName() string {
	if x != nil {
		if x.xxx_hidden_TaskName != nil {
			return *x.xxx_hidden_TaskName
		}
		return ""
	}
	return ""
}

func (x *TaskAppendLog_Input) GetLog() string {
	if x != nil {
		if x.xxx_hidden_Log != nil {
			return *x.xxx_hidden_Log
		}
		return ""
	}
	return ""
}

func (x *TaskAppendLog_Input) SetTaskName(v string) {
	x.xxx_hidden_TaskName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *TaskAppendLog_Input) SetLog(v string) {
	x.xxx_hidden_Log = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *TaskAppendLog_Input) HasTaskName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TaskAppendLog_Input) HasLog() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TaskAppendLog_Input) ClearTaskName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TaskName = nil
}

func (x *TaskAppendLog_Input) ClearLog() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Log = nil
}

type TaskAppendLog_Input_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskName *string
	Log      *string
}

func (b0 TaskAppendLog_Input_builder) Build() *TaskAppendLog_Input {
	m0 := &TaskAppendLog_Input{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TaskName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_TaskName = b.TaskName
	}
	if b.Log != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Log = b.Log
	}
	return m0
}

type TaskAppendLog_Output struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAppendLog_Output) Reset() {
	*x = TaskAppendLog_Output{}
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAppendLog_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAppendLog_Output) ProtoMessage() {}

func (x *TaskAppendLog_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_TaskExecution_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type TaskAppendLog_Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 TaskAppendLog_Output_builder) Build() *TaskAppendLog_Output {
	m0 := &TaskAppendLog_Output{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_kk_scheduler_TaskExecution_proto protoreflect.FileDescriptor

const file_kk_scheduler_TaskExecution_proto_rawDesc = "" +
	"\n" +
	" kk_scheduler/TaskExecution.proto\x12\fkk_scheduler\x1a\x1fkk_scheduler/extend_field.proto\"B\n" +
	"\n" +
	"TaskCreate\x1a*\n" +
	"\x05Input\x12!\n" +
	"\ttask_name\x18\x01 \x01(\tB\x04\xca>\x01\x01R\btaskName\x1a\b\n" +
	"\x06Output\"\x89\x01\n" +
	"\x10TaskUpdateStatus\x1ak\n" +
	"\x05Input\x12!\n" +
	"\ttask_name\x18\x01 \x01(\tB\x04\xca>\x01\x01R\btaskName\x12?\n" +
	"\x06status\x18\x02 \x01(\x0e2!.kk_scheduler.TaskExecutionStatusB\x04\xca>\x01\x01R\x06status\x1a\b\n" +
	"\x06Output\"]\n" +
	"\rTaskAppendLog\x1aB\n" +
	"\x05Input\x12!\n" +
	"\ttask_name\x18\x01 \x01(\tB\x04\xca>\x01\x01R\btaskName\x12\x16\n" +
	"\x03log\x18\x02 \x01(\tB\x04\xca>\x01\x01R\x03log\x1a\b\n" +
	"\x06Output*\xa6\x01\n" +
	"\x13TaskExecutionStatus\x12%\n" +
	"!TASK_EXECUTION_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dTASK_EXECUTION_STATUS_RUNNING\x10\x01\x12#\n" +
	"\x1fTASK_EXECUTION_STATUS_COMPLETED\x10\x02\x12 \n" +
	"\x1cTASK_EXECUTION_STATUS_FAILED\x10\x03B\x0fZ\r/kk_schedulerb\beditionsp\xe8\a"

var file_kk_scheduler_TaskExecution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kk_scheduler_TaskExecution_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_kk_scheduler_TaskExecution_proto_goTypes = []any{
	(TaskExecutionStatus)(0),        // 0: kk_scheduler.TaskExecutionStatus
	(*TaskCreate)(nil),              // 1: kk_scheduler.TaskCreate
	(*TaskUpdateStatus)(nil),        // 2: kk_scheduler.TaskUpdateStatus
	(*TaskAppendLog)(nil),           // 3: kk_scheduler.TaskAppendLog
	(*TaskCreate_Input)(nil),        // 4: kk_scheduler.TaskCreate.Input
	(*TaskCreate_Output)(nil),       // 5: kk_scheduler.TaskCreate.Output
	(*TaskUpdateStatus_Input)(nil),  // 6: kk_scheduler.TaskUpdateStatus.Input
	(*TaskUpdateStatus_Output)(nil), // 7: kk_scheduler.TaskUpdateStatus.Output
	(*TaskAppendLog_Input)(nil),     // 8: kk_scheduler.TaskAppendLog.Input
	(*TaskAppendLog_Output)(nil),    // 9: kk_scheduler.TaskAppendLog.Output
}
var file_kk_scheduler_TaskExecution_proto_depIdxs = []int32{
	0, // 0: kk_scheduler.TaskUpdateStatus.Input.status:type_name -> kk_scheduler.TaskExecutionStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kk_scheduler_TaskExecution_proto_init() }
func file_kk_scheduler_TaskExecution_proto_init() {
	if File_kk_scheduler_TaskExecution_proto != nil {
		return
	}
	file_kk_scheduler_extend_field_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_scheduler_TaskExecution_proto_rawDesc), len(file_kk_scheduler_TaskExecution_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_scheduler_TaskExecution_proto_goTypes,
		DependencyIndexes: file_kk_scheduler_TaskExecution_proto_depIdxs,
		EnumInfos:         file_kk_scheduler_TaskExecution_proto_enumTypes,
		MessageInfos:      file_kk_scheduler_TaskExecution_proto_msgTypes,
	}.Build()
	File_kk_scheduler_TaskExecution_proto = out.File
	file_kk_scheduler_TaskExecution_proto_goTypes = nil
	file_kk_scheduler_TaskExecution_proto_depIdxs = nil
}
