name: kk-scheduler
services:
  kk-scheduler:
    image: cruvie/kk-scheduler:latest
    container_name: kk-scheduler
    restart: unless-stopped
    environment:
      KK_Schedule: "prod"
    depends_on:
      - test-postgres
    ports:
      - "8666:8666"
      - "8667:8667"
      - "8668:8668"
    volumes:
      - ./config.toml:/kk-scheduler/config.toml
      - ./logs:/kk-scheduler/logs

  test-postgres:
    image: postgres:latest
    container_name: test-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpg
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql