// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kk_schedule/JobSetSpec.proto

package kk_schedule

import (
	_ "gitee.com/cruvie/kk_go_kit/kk_protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobSetSpec struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSetSpec) Reset() {
	*x = JobSetSpec{}
	mi := &file_kk_schedule_JobSetSpec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSetSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSetSpec) ProtoMessage() {}

func (x *JobSetSpec) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_JobSetSpec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type JobSetSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 JobSetSpec_builder) Build() *JobSetSpec {
	m0 := &JobSetSpec{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type JobSetSpec_Input struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ServiceName *string                `protobuf:"bytes,1,opt,name=serviceName"`
	xxx_hidden_FuncName    *string                `protobuf:"bytes,2,opt,name=funcName"`
	xxx_hidden_Spec        *string                `protobuf:"bytes,3,opt,name=spec"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *JobSetSpec_Input) Reset() {
	*x = JobSetSpec_Input{}
	mi := &file_kk_schedule_JobSetSpec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSetSpec_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSetSpec_Input) ProtoMessage() {}

func (x *JobSetSpec_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_JobSetSpec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobSetSpec_Input) GetServiceName() string {
	if x != nil {
		if x.xxx_hidden_ServiceName != nil {
			return *x.xxx_hidden_ServiceName
		}
		return ""
	}
	return ""
}

func (x *JobSetSpec_Input) GetFuncName() string {
	if x != nil {
		if x.xxx_hidden_FuncName != nil {
			return *x.xxx_hidden_FuncName
		}
		return ""
	}
	return ""
}

func (x *JobSetSpec_Input) GetSpec() string {
	if x != nil {
		if x.xxx_hidden_Spec != nil {
			return *x.xxx_hidden_Spec
		}
		return ""
	}
	return ""
}

func (x *JobSetSpec_Input) SetServiceName(v string) {
	x.xxx_hidden_ServiceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *JobSetSpec_Input) SetFuncName(v string) {
	x.xxx_hidden_FuncName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *JobSetSpec_Input) SetSpec(v string) {
	x.xxx_hidden_Spec = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *JobSetSpec_Input) HasServiceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *JobSetSpec_Input) HasFuncName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *JobSetSpec_Input) HasSpec() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *JobSetSpec_Input) ClearServiceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ServiceName = nil
}

func (x *JobSetSpec_Input) ClearFuncName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_FuncName = nil
}

func (x *JobSetSpec_Input) ClearSpec() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Spec = nil
}

type JobSetSpec_Input_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ServiceName *string
	FuncName    *string
	Spec        *string
}

func (b0 JobSetSpec_Input_builder) Build() *JobSetSpec_Input {
	m0 := &JobSetSpec_Input{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ServiceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_ServiceName = b.ServiceName
	}
	if b.FuncName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_FuncName = b.FuncName
	}
	if b.Spec != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Spec = b.Spec
	}
	return m0
}

type JobSetSpec_Output struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSetSpec_Output) Reset() {
	*x = JobSetSpec_Output{}
	mi := &file_kk_schedule_JobSetSpec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSetSpec_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSetSpec_Output) ProtoMessage() {}

func (x *JobSetSpec_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_JobSetSpec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type JobSetSpec_Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 JobSetSpec_Output_builder) Build() *JobSetSpec_Output {
	m0 := &JobSetSpec_Output{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_kk_schedule_JobSetSpec_proto protoreflect.FileDescriptor

const file_kk_schedule_JobSetSpec_proto_rawDesc = "" +
	"\n" +
	"\x1ckk_schedule/JobSetSpec.proto\x12\vkk_schedule\x1a@vendor/gitee.com/cruvie/kk_go_kit/kk_protobuf/extend_field.proto\"\x86\x01\n" +
	"\n" +
	"JobSetSpec\x1an\n" +
	"\x05Input\x12'\n" +
	"\vserviceName\x18\x01 \x01(\tB\x05\x8a\xa6\x1d\x01\x01R\vserviceName\x12!\n" +
	"\bfuncName\x18\x02 \x01(\tB\x05\x8a\xa6\x1d\x01\x01R\bfuncName\x12\x19\n" +
	"\x04spec\x18\x03 \x01(\tB\x05\x8a\xa6\x1d\x01\x01R\x04spec\x1a\b\n" +
	"\x06OutputB\x0eZ\f/kk_scheduleb\beditionsp\xe8\a"

var file_kk_schedule_JobSetSpec_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_schedule_JobSetSpec_proto_goTypes = []any{
	(*JobSetSpec)(nil),        // 0: kk_schedule.JobSetSpec
	(*JobSetSpec_Input)(nil),  // 1: kk_schedule.JobSetSpec.Input
	(*JobSetSpec_Output)(nil), // 2: kk_schedule.JobSetSpec.Output
}
var file_kk_schedule_JobSetSpec_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kk_schedule_JobSetSpec_proto_init() }
func file_kk_schedule_JobSetSpec_proto_init() {
	if File_kk_schedule_JobSetSpec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_schedule_JobSetSpec_proto_rawDesc), len(file_kk_schedule_JobSetSpec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_schedule_JobSetSpec_proto_goTypes,
		DependencyIndexes: file_kk_schedule_JobSetSpec_proto_depIdxs,
		MessageInfos:      file_kk_schedule_JobSetSpec_proto_msgTypes,
	}.Build()
	File_kk_schedule_JobSetSpec_proto = out.File
	file_kk_schedule_JobSetSpec_proto_goTypes = nil
	file_kk_schedule_JobSetSpec_proto_depIdxs = nil
}
