// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kk_schedule/ServicePut.proto

package kk_schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServicePut struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePut) Reset() {
	*x = ServicePut{}
	mi := &file_kk_schedule_ServicePut_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePut) ProtoMessage() {}

func (x *ServicePut) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_ServicePut_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ServicePut_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ServicePut_builder) Build() *ServicePut {
	m0 := &ServicePut{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ServicePut_Input struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Service *PBRegisterService     `protobuf:"bytes,1,opt,name=Service"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServicePut_Input) Reset() {
	*x = ServicePut_Input{}
	mi := &file_kk_schedule_ServicePut_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePut_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePut_Input) ProtoMessage() {}

func (x *ServicePut_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_ServicePut_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServicePut_Input) GetService() *PBRegisterService {
	if x != nil {
		return x.xxx_hidden_Service
	}
	return nil
}

func (x *ServicePut_Input) SetService(v *PBRegisterService) {
	x.xxx_hidden_Service = v
}

func (x *ServicePut_Input) HasService() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Service != nil
}

func (x *ServicePut_Input) ClearService() {
	x.xxx_hidden_Service = nil
}

type ServicePut_Input_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Service *PBRegisterService
}

func (b0 ServicePut_Input_builder) Build() *ServicePut_Input {
	m0 := &ServicePut_Input{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Service = b.Service
	return m0
}

type ServicePut_Output struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePut_Output) Reset() {
	*x = ServicePut_Output{}
	mi := &file_kk_schedule_ServicePut_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePut_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePut_Output) ProtoMessage() {}

func (x *ServicePut_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_ServicePut_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ServicePut_Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ServicePut_Output_builder) Build() *ServicePut_Output {
	m0 := &ServicePut_Output{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_kk_schedule_ServicePut_proto protoreflect.FileDescriptor

const file_kk_schedule_ServicePut_proto_rawDesc = "" +
	"\n" +
	"\x1ckk_schedule/ServicePut.proto\x12\vkk_schedule\x1a\x16kk_schedule/Base.proto\"Y\n" +
	"\n" +
	"ServicePut\x1aA\n" +
	"\x05Input\x128\n" +
	"\aService\x18\x01 \x01(\v2\x1e.kk_schedule.PBRegisterServiceR\aService\x1a\b\n" +
	"\x06OutputB\x0eZ\f/kk_scheduleb\beditionsp\xe8\a"

var file_kk_schedule_ServicePut_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_schedule_ServicePut_proto_goTypes = []any{
	(*ServicePut)(nil),        // 0: kk_schedule.ServicePut
	(*ServicePut_Input)(nil),  // 1: kk_schedule.ServicePut.Input
	(*ServicePut_Output)(nil), // 2: kk_schedule.ServicePut.Output
	(*PBRegisterService)(nil), // 3: kk_schedule.PBRegisterService
}
var file_kk_schedule_ServicePut_proto_depIdxs = []int32{
	3, // 0: kk_schedule.ServicePut.Input.Service:type_name -> kk_schedule.PBRegisterService
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kk_schedule_ServicePut_proto_init() }
func file_kk_schedule_ServicePut_proto_init() {
	if File_kk_schedule_ServicePut_proto != nil {
		return
	}
	file_kk_schedule_Base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_schedule_ServicePut_proto_rawDesc), len(file_kk_schedule_ServicePut_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_schedule_ServicePut_proto_goTypes,
		DependencyIndexes: file_kk_schedule_ServicePut_proto_depIdxs,
		MessageInfos:      file_kk_schedule_ServicePut_proto_msgTypes,
	}.Build()
	File_kk_schedule_ServicePut_proto = out.File
	file_kk_schedule_ServicePut_proto_goTypes = nil
	file_kk_schedule_ServicePut_proto_depIdxs = nil
}
