// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kk_schedule/ServiceDelete.proto

package kk_schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceDelete struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDelete) Reset() {
	*x = ServiceDelete{}
	mi := &file_kk_schedule_ServiceDelete_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDelete) ProtoMessage() {}

func (x *ServiceDelete) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_ServiceDelete_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ServiceDelete_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ServiceDelete_builder) Build() *ServiceDelete {
	m0 := &ServiceDelete{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ServiceDelete_Input struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ServiceName *string                `protobuf:"bytes,1,opt,name=ServiceName"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ServiceDelete_Input) Reset() {
	*x = ServiceDelete_Input{}
	mi := &file_kk_schedule_ServiceDelete_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDelete_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDelete_Input) ProtoMessage() {}

func (x *ServiceDelete_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_ServiceDelete_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServiceDelete_Input) GetServiceName() string {
	if x != nil {
		if x.xxx_hidden_ServiceName != nil {
			return *x.xxx_hidden_ServiceName
		}
		return ""
	}
	return ""
}

func (x *ServiceDelete_Input) SetServiceName(v string) {
	x.xxx_hidden_ServiceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ServiceDelete_Input) HasServiceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ServiceDelete_Input) ClearServiceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ServiceName = nil
}

type ServiceDelete_Input_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ServiceName *string
}

func (b0 ServiceDelete_Input_builder) Build() *ServiceDelete_Input {
	m0 := &ServiceDelete_Input{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ServiceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ServiceName = b.ServiceName
	}
	return m0
}

type ServiceDelete_Output struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDelete_Output) Reset() {
	*x = ServiceDelete_Output{}
	mi := &file_kk_schedule_ServiceDelete_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDelete_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDelete_Output) ProtoMessage() {}

func (x *ServiceDelete_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_ServiceDelete_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ServiceDelete_Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ServiceDelete_Output_builder) Build() *ServiceDelete_Output {
	m0 := &ServiceDelete_Output{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_kk_schedule_ServiceDelete_proto protoreflect.FileDescriptor

const file_kk_schedule_ServiceDelete_proto_rawDesc = "" +
	"\n" +
	"\x1fkk_schedule/ServiceDelete.proto\x12\vkk_schedule\"D\n" +
	"\rServiceDelete\x1a)\n" +
	"\x05Input\x12 \n" +
	"\vServiceName\x18\x01 \x01(\tR\vServiceName\x1a\b\n" +
	"\x06OutputB\x0eZ\f/kk_scheduleb\beditionsp\xe8\a"

var file_kk_schedule_ServiceDelete_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_schedule_ServiceDelete_proto_goTypes = []any{
	(*ServiceDelete)(nil),        // 0: kk_schedule.ServiceDelete
	(*ServiceDelete_Input)(nil),  // 1: kk_schedule.ServiceDelete.Input
	(*ServiceDelete_Output)(nil), // 2: kk_schedule.ServiceDelete.Output
}
var file_kk_schedule_ServiceDelete_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kk_schedule_ServiceDelete_proto_init() }
func file_kk_schedule_ServiceDelete_proto_init() {
	if File_kk_schedule_ServiceDelete_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_schedule_ServiceDelete_proto_rawDesc), len(file_kk_schedule_ServiceDelete_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_schedule_ServiceDelete_proto_goTypes,
		DependencyIndexes: file_kk_schedule_ServiceDelete_proto_depIdxs,
		MessageInfos:      file_kk_schedule_ServiceDelete_proto_msgTypes,
	}.Build()
	File_kk_schedule_ServiceDelete_proto = out.File
	file_kk_schedule_ServiceDelete_proto_goTypes = nil
	file_kk_schedule_ServiceDelete_proto_depIdxs = nil
}
