// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kk_schedule/service.proto

package kk_schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_kk_schedule_service_proto protoreflect.FileDescriptor

const file_kk_schedule_service_proto_rawDesc = "" +
	"\n" +
	"\x19kk_schedule/service.proto\x12\vkk_schedule\x1a\x19kk_schedule/JobList.proto\x1a\x18kk_schedule/JobGet.proto\x1a\x1bkk_schedule/JobEnable.proto\x1a\x1ckk_schedule/JobDisable.proto\x1a\x1ckk_schedule/JobSetSpec.proto\x1a\x18kk_schedule/JobPut.proto\x1a\x1dkk_schedule/ServiceList.proto\x1a\x1ckk_schedule/ServicePut.proto\x1a\x1ckk_schedule/ServiceGet.proto\x1a\x1fkk_schedule/ServiceDelete.proto\x1a\x1bkk_schedule/JobDelete.proto\x1a\x1ckk_schedule/JobTrigger.proto2\x8d\a\n" +
	"\n" +
	"KKSchedule\x12B\n" +
	"\aJobList\x12\x1a.kk_schedule.JobList.Input\x1a\x1b.kk_schedule.JobList.Output\x12?\n" +
	"\x06JobGet\x12\x19.kk_schedule.JobGet.Input\x1a\x1a.kk_schedule.JobGet.Output\x12K\n" +
	"\n" +
	"JobSetSpec\x12\x1d.kk_schedule.JobSetSpec.Input\x1a\x1e.kk_schedule.JobSetSpec.Output\x12H\n" +
	"\tJobEnable\x12\x1c.kk_schedule.JobEnable.Input\x1a\x1d.kk_schedule.JobEnable.Output\x12K\n" +
	"\n" +
	"JobDisable\x12\x1d.kk_schedule.JobDisable.Input\x1a\x1e.kk_schedule.JobDisable.Output\x12?\n" +
	"\x06JobPut\x12\x19.kk_schedule.JobPut.Input\x1a\x1a.kk_schedule.JobPut.Output\x12H\n" +
	"\tJobDelete\x12\x1c.kk_schedule.JobDelete.Input\x1a\x1d.kk_schedule.JobDelete.Output\x12K\n" +
	"\n" +
	"JobTrigger\x12\x1d.kk_schedule.JobTrigger.Input\x1a\x1e.kk_schedule.JobTrigger.Output\x12N\n" +
	"\vServiceList\x12\x1e.kk_schedule.ServiceList.Input\x1a\x1f.kk_schedule.ServiceList.Output\x12K\n" +
	"\n" +
	"ServicePut\x12\x1d.kk_schedule.ServicePut.Input\x1a\x1e.kk_schedule.ServicePut.Output\x12K\n" +
	"\n" +
	"ServiceGet\x12\x1d.kk_schedule.ServiceGet.Input\x1a\x1e.kk_schedule.ServiceGet.Output\x12T\n" +
	"\rServiceDelete\x12 .kk_schedule.ServiceDelete.Input\x1a!.kk_schedule.ServiceDelete.OutputB\x0eZ\f/kk_scheduleb\beditionsp\xe8\a"

var file_kk_schedule_service_proto_goTypes = []any{
	(*JobList_Input)(nil),        // 0: kk_schedule.JobList.Input
	(*JobGet_Input)(nil),         // 1: kk_schedule.JobGet.Input
	(*JobSetSpec_Input)(nil),     // 2: kk_schedule.JobSetSpec.Input
	(*JobEnable_Input)(nil),      // 3: kk_schedule.JobEnable.Input
	(*JobDisable_Input)(nil),     // 4: kk_schedule.JobDisable.Input
	(*JobPut_Input)(nil),         // 5: kk_schedule.JobPut.Input
	(*JobDelete_Input)(nil),      // 6: kk_schedule.JobDelete.Input
	(*JobTrigger_Input)(nil),     // 7: kk_schedule.JobTrigger.Input
	(*ServiceList_Input)(nil),    // 8: kk_schedule.ServiceList.Input
	(*ServicePut_Input)(nil),     // 9: kk_schedule.ServicePut.Input
	(*ServiceGet_Input)(nil),     // 10: kk_schedule.ServiceGet.Input
	(*ServiceDelete_Input)(nil),  // 11: kk_schedule.ServiceDelete.Input
	(*JobList_Output)(nil),       // 12: kk_schedule.JobList.Output
	(*JobGet_Output)(nil),        // 13: kk_schedule.JobGet.Output
	(*JobSetSpec_Output)(nil),    // 14: kk_schedule.JobSetSpec.Output
	(*JobEnable_Output)(nil),     // 15: kk_schedule.JobEnable.Output
	(*JobDisable_Output)(nil),    // 16: kk_schedule.JobDisable.Output
	(*JobPut_Output)(nil),        // 17: kk_schedule.JobPut.Output
	(*JobDelete_Output)(nil),     // 18: kk_schedule.JobDelete.Output
	(*JobTrigger_Output)(nil),    // 19: kk_schedule.JobTrigger.Output
	(*ServiceList_Output)(nil),   // 20: kk_schedule.ServiceList.Output
	(*ServicePut_Output)(nil),    // 21: kk_schedule.ServicePut.Output
	(*ServiceGet_Output)(nil),    // 22: kk_schedule.ServiceGet.Output
	(*ServiceDelete_Output)(nil), // 23: kk_schedule.ServiceDelete.Output
}
var file_kk_schedule_service_proto_depIdxs = []int32{
	0,  // 0: kk_schedule.KKSchedule.JobList:input_type -> kk_schedule.JobList.Input
	1,  // 1: kk_schedule.KKSchedule.JobGet:input_type -> kk_schedule.JobGet.Input
	2,  // 2: kk_schedule.KKSchedule.JobSetSpec:input_type -> kk_schedule.JobSetSpec.Input
	3,  // 3: kk_schedule.KKSchedule.JobEnable:input_type -> kk_schedule.JobEnable.Input
	4,  // 4: kk_schedule.KKSchedule.JobDisable:input_type -> kk_schedule.JobDisable.Input
	5,  // 5: kk_schedule.KKSchedule.JobPut:input_type -> kk_schedule.JobPut.Input
	6,  // 6: kk_schedule.KKSchedule.JobDelete:input_type -> kk_schedule.JobDelete.Input
	7,  // 7: kk_schedule.KKSchedule.JobTrigger:input_type -> kk_schedule.JobTrigger.Input
	8,  // 8: kk_schedule.KKSchedule.ServiceList:input_type -> kk_schedule.ServiceList.Input
	9,  // 9: kk_schedule.KKSchedule.ServicePut:input_type -> kk_schedule.ServicePut.Input
	10, // 10: kk_schedule.KKSchedule.ServiceGet:input_type -> kk_schedule.ServiceGet.Input
	11, // 11: kk_schedule.KKSchedule.ServiceDelete:input_type -> kk_schedule.ServiceDelete.Input
	12, // 12: kk_schedule.KKSchedule.JobList:output_type -> kk_schedule.JobList.Output
	13, // 13: kk_schedule.KKSchedule.JobGet:output_type -> kk_schedule.JobGet.Output
	14, // 14: kk_schedule.KKSchedule.JobSetSpec:output_type -> kk_schedule.JobSetSpec.Output
	15, // 15: kk_schedule.KKSchedule.JobEnable:output_type -> kk_schedule.JobEnable.Output
	16, // 16: kk_schedule.KKSchedule.JobDisable:output_type -> kk_schedule.JobDisable.Output
	17, // 17: kk_schedule.KKSchedule.JobPut:output_type -> kk_schedule.JobPut.Output
	18, // 18: kk_schedule.KKSchedule.JobDelete:output_type -> kk_schedule.JobDelete.Output
	19, // 19: kk_schedule.KKSchedule.JobTrigger:output_type -> kk_schedule.JobTrigger.Output
	20, // 20: kk_schedule.KKSchedule.ServiceList:output_type -> kk_schedule.ServiceList.Output
	21, // 21: kk_schedule.KKSchedule.ServicePut:output_type -> kk_schedule.ServicePut.Output
	22, // 22: kk_schedule.KKSchedule.ServiceGet:output_type -> kk_schedule.ServiceGet.Output
	23, // 23: kk_schedule.KKSchedule.ServiceDelete:output_type -> kk_schedule.ServiceDelete.Output
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_kk_schedule_service_proto_init() }
func file_kk_schedule_service_proto_init() {
	if File_kk_schedule_service_proto != nil {
		return
	}
	file_kk_schedule_JobList_proto_init()
	file_kk_schedule_JobGet_proto_init()
	file_kk_schedule_JobEnable_proto_init()
	file_kk_schedule_JobDisable_proto_init()
	file_kk_schedule_JobSetSpec_proto_init()
	file_kk_schedule_JobPut_proto_init()
	file_kk_schedule_ServiceList_proto_init()
	file_kk_schedule_ServicePut_proto_init()
	file_kk_schedule_ServiceGet_proto_init()
	file_kk_schedule_ServiceDelete_proto_init()
	file_kk_schedule_JobDelete_proto_init()
	file_kk_schedule_JobTrigger_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_schedule_service_proto_rawDesc), len(file_kk_schedule_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kk_schedule_service_proto_goTypes,
		DependencyIndexes: file_kk_schedule_service_proto_depIdxs,
	}.Build()
	File_kk_schedule_service_proto = out.File
	file_kk_schedule_service_proto_goTypes = nil
	file_kk_schedule_service_proto_depIdxs = nil
}
