// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kk_schedule/trigger.proto

package kk_schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trigger struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trigger) Reset() {
	*x = Trigger{}
	mi := &file_kk_schedule_trigger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger) ProtoMessage() {}

func (x *Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_trigger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Trigger_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Trigger_builder) Build() *Trigger {
	m0 := &Trigger{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type Trigger_Input struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FuncName    *string                `protobuf:"bytes,1,opt,name=funcName"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Trigger_Input) Reset() {
	*x = Trigger_Input{}
	mi := &file_kk_schedule_trigger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger_Input) ProtoMessage() {}

func (x *Trigger_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_trigger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Trigger_Input) GetFuncName() string {
	if x != nil {
		if x.xxx_hidden_FuncName != nil {
			return *x.xxx_hidden_FuncName
		}
		return ""
	}
	return ""
}

func (x *Trigger_Input) SetFuncName(v string) {
	x.xxx_hidden_FuncName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Trigger_Input) HasFuncName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Trigger_Input) ClearFuncName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FuncName = nil
}

type Trigger_Input_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FuncName *string
}

func (b0 Trigger_Input_builder) Build() *Trigger_Input {
	m0 := &Trigger_Input{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FuncName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_FuncName = b.FuncName
	}
	return m0
}

type Trigger_Output struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trigger_Output) Reset() {
	*x = Trigger_Output{}
	mi := &file_kk_schedule_trigger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger_Output) ProtoMessage() {}

func (x *Trigger_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_trigger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Trigger_Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Trigger_Output_builder) Build() *Trigger_Output {
	m0 := &Trigger_Output{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_kk_schedule_trigger_proto protoreflect.FileDescriptor

const file_kk_schedule_trigger_proto_rawDesc = "" +
	"\n" +
	"\x19kk_schedule/trigger.proto\x12\vkk_schedule\"8\n" +
	"\aTrigger\x1a#\n" +
	"\x05Input\x12\x1a\n" +
	"\bfuncName\x18\x01 \x01(\tR\bfuncName\x1a\b\n" +
	"\x06Output2W\n" +
	"\x11KKScheduleTrigger\x12B\n" +
	"\aTrigger\x12\x1a.kk_schedule.Trigger.Input\x1a\x1b.kk_schedule.Trigger.OutputB\x0eZ\f/kk_scheduleb\beditionsp\xe8\a"

var file_kk_schedule_trigger_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_schedule_trigger_proto_goTypes = []any{
	(*Trigger)(nil),        // 0: kk_schedule.Trigger
	(*Trigger_Input)(nil),  // 1: kk_schedule.Trigger.Input
	(*Trigger_Output)(nil), // 2: kk_schedule.Trigger.Output
}
var file_kk_schedule_trigger_proto_depIdxs = []int32{
	1, // 0: kk_schedule.KKScheduleTrigger.Trigger:input_type -> kk_schedule.Trigger.Input
	2, // 1: kk_schedule.KKScheduleTrigger.Trigger:output_type -> kk_schedule.Trigger.Output
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kk_schedule_trigger_proto_init() }
func file_kk_schedule_trigger_proto_init() {
	if File_kk_schedule_trigger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_schedule_trigger_proto_rawDesc), len(file_kk_schedule_trigger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kk_schedule_trigger_proto_goTypes,
		DependencyIndexes: file_kk_schedule_trigger_proto_depIdxs,
		MessageInfos:      file_kk_schedule_trigger_proto_msgTypes,
	}.Build()
	File_kk_schedule_trigger_proto = out.File
	file_kk_schedule_trigger_proto_goTypes = nil
	file_kk_schedule_trigger_proto_depIdxs = nil
}
