// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: kk_schedule/trigger.proto

package kk_schedule

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KKScheduleTrigger_Trigger_FullMethodName = "/kk_schedule.KKScheduleTrigger/Trigger"
)

// KKScheduleTriggerClient is the client API for KKScheduleTrigger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KKScheduleTriggerClient interface {
	Trigger(ctx context.Context, in *Trigger_Input, opts ...grpc.CallOption) (*Trigger_Output, error)
}

type kKScheduleTriggerClient struct {
	cc grpc.ClientConnInterface
}

func NewKKScheduleTriggerClient(cc grpc.ClientConnInterface) KKScheduleTriggerClient {
	return &kKScheduleTriggerClient{cc}
}

func (c *kKScheduleTriggerClient) Trigger(ctx context.Context, in *Trigger_Input, opts ...grpc.CallOption) (*Trigger_Output, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Trigger_Output)
	err := c.cc.Invoke(ctx, KKScheduleTrigger_Trigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KKScheduleTriggerServer is the server API for KKScheduleTrigger service.
// All implementations must embed UnimplementedKKScheduleTriggerServer
// for forward compatibility.
type KKScheduleTriggerServer interface {
	Trigger(context.Context, *Trigger_Input) (*Trigger_Output, error)
	mustEmbedUnimplementedKKScheduleTriggerServer()
}

// UnimplementedKKScheduleTriggerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKKScheduleTriggerServer struct{}

func (UnimplementedKKScheduleTriggerServer) Trigger(context.Context, *Trigger_Input) (*Trigger_Output, error) {
	return nil, status.Error(codes.Unimplemented, "method Trigger not implemented")
}
func (UnimplementedKKScheduleTriggerServer) mustEmbedUnimplementedKKScheduleTriggerServer() {}
func (UnimplementedKKScheduleTriggerServer) testEmbeddedByValue()                           {}

// UnsafeKKScheduleTriggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KKScheduleTriggerServer will
// result in compilation errors.
type UnsafeKKScheduleTriggerServer interface {
	mustEmbedUnimplementedKKScheduleTriggerServer()
}

func RegisterKKScheduleTriggerServer(s grpc.ServiceRegistrar, srv KKScheduleTriggerServer) {
	// If the following call panics, it indicates UnimplementedKKScheduleTriggerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KKScheduleTrigger_ServiceDesc, srv)
}

func _KKScheduleTrigger_Trigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Trigger_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KKScheduleTriggerServer).Trigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KKScheduleTrigger_Trigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KKScheduleTriggerServer).Trigger(ctx, req.(*Trigger_Input))
	}
	return interceptor(ctx, in, info, handler)
}

// KKScheduleTrigger_ServiceDesc is the grpc.ServiceDesc for KKScheduleTrigger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KKScheduleTrigger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kk_schedule.KKScheduleTrigger",
	HandlerType: (*KKScheduleTriggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Trigger",
			Handler:    _KKScheduleTrigger_Trigger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kk_schedule/trigger.proto",
}
